// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gym-uds.proto

#include "gym-uds.pb.h"
#include "gym-uds.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* Environment_method_names[] = {
  "/Environment/Reset",
  "/Environment/Step",
  "/Environment/Sample",
};

std::unique_ptr< Environment::Stub> Environment::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Environment::Stub> stub(new Environment::Stub(channel));
  return stub;
}

Environment::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Reset_(Environment_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Step_(Environment_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Sample_(Environment_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Environment::Stub::Reset(::grpc::ClientContext* context, const ::Empty& request, ::State* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Reset_, context, request, response);
}

void Environment::Stub::experimental_async::Reset(::grpc::ClientContext* context, const ::Empty* request, ::State* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Reset_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::State>* Environment::Stub::AsyncResetRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::State>::Create(channel_.get(), cq, rpcmethod_Reset_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::State>* Environment::Stub::PrepareAsyncResetRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::State>::Create(channel_.get(), cq, rpcmethod_Reset_, context, request, false);
}

::grpc::Status Environment::Stub::Step(::grpc::ClientContext* context, const ::Action& request, ::State* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Step_, context, request, response);
}

void Environment::Stub::experimental_async::Step(::grpc::ClientContext* context, const ::Action* request, ::State* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Step_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::State>* Environment::Stub::AsyncStepRaw(::grpc::ClientContext* context, const ::Action& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::State>::Create(channel_.get(), cq, rpcmethod_Step_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::State>* Environment::Stub::PrepareAsyncStepRaw(::grpc::ClientContext* context, const ::Action& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::State>::Create(channel_.get(), cq, rpcmethod_Step_, context, request, false);
}

::grpc::Status Environment::Stub::Sample(::grpc::ClientContext* context, const ::Empty& request, ::Action* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Sample_, context, request, response);
}

void Environment::Stub::experimental_async::Sample(::grpc::ClientContext* context, const ::Empty* request, ::Action* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Sample_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::Action>* Environment::Stub::AsyncSampleRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Action>::Create(channel_.get(), cq, rpcmethod_Sample_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Action>* Environment::Stub::PrepareAsyncSampleRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Action>::Create(channel_.get(), cq, rpcmethod_Sample_, context, request, false);
}

Environment::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Environment_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Environment::Service, ::Empty, ::State>(
          std::mem_fn(&Environment::Service::Reset), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Environment_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Environment::Service, ::Action, ::State>(
          std::mem_fn(&Environment::Service::Step), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Environment_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Environment::Service, ::Empty, ::Action>(
          std::mem_fn(&Environment::Service::Sample), this)));
}

Environment::Service::~Service() {
}

::grpc::Status Environment::Service::Reset(::grpc::ServerContext* context, const ::Empty* request, ::State* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Environment::Service::Step(::grpc::ServerContext* context, const ::Action* request, ::State* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Environment::Service::Sample(::grpc::ServerContext* context, const ::Empty* request, ::Action* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


